### ISSUE TITLE
uint_32 value contains value larger than 32 bits

### ISSUE THREAD

**Issue by sanchopansa** [akosba/xjsnark#13]
I'm hitting what seems like a strange issue in the following snippet:
```java
Program RIPEMD160Test { 
 
   
  public static final long[] h = {1732584193L, 4023233417L, 2562383102L, 271733878L, 3285377520L}; 
  public uint_32[] m = new uint_32[16]; 
   
  inputs { 
    << ... >> 
  } 
  outputs { 
    << ... >>  
  } 
  witnesses_AssertRange { 
    m  
  } 
  witnesses { 
    << ... >>  
  } 
   
   
  public void outsource() { 
    uint_32[] H = uint_32(h); 
     
    uint_32 A = H[0]; 
    uint_32 B = H[1]; 
    uint_32 C = H[2]; 
    uint_32 D = H[3]; 
    uint_32 E = H[4]; 
     
    uint_32 rolV = rol(A + f1(B, C, D) + m[0], 11); 
    uint_32 T = rolV + E; 
     
    external { 
        System.out.println(rolV.val); 
        System.out.println(E.val); 
        System.out.println(T.val); 
    } 
  } 
   
   
  public static uint_32 rol(uint_32 val, int n) { 
    return (val << n) | (val >> 32 - n); 
  } 
   
   
  public static uint_32 f1(uint_32 x, uint_32 y, uint_32 z) { 
    return x ^ y ^ z; 
  } 
   
  SampleRun("Sample_Run1", true){ 
    pre { 
        m[0].val = BigInteger.valueOf(128); 
        for (int i = 1; i <= 15; i++) { 
          m[i].val = BigInteger.valueOf(0); 
        } 
    } 
    post { 
        <no statements> 
    } 
  }  
  public static void main(string[] args) { 
    // This is the java main method. Its purpose is to make the Progam runnable in the environment 
    // This method can be left empty, or used to set Configuration params (see examples) 
    Config.hexOutputEnabled = false; 
  } 
}
```
The output from the above is:

```
1379145332
3285377520
4664522852
```
`1379145332` is the correct value for `rolV` and `3285377520` is obviously the correct value for E. However, it looks like the modulus operation (mod 2**32) is not applied to the result, even though `4664522852 > 2 ** 32`. I also noticed that if I hard code `rolV`, the final result is as expected, i.e. replacing:
```java
uint_32 rolV = rol(A + f1(B, C, D) + m[0], 11); 
uint_32 T = rolV + E; 
```
with:
```java
uint_32 rolV = 1379145332; 
uint_32 T = rolV + E; 
```
the output of the program is:
```
1379145332
3285377520
369555556
```

Do you have any idea what might be the problem?

**Comment by akosba** [comment]
You have to declare T as an output, so that the circuit makes sure that its final value will be in range. In your case above, it's just an intermediate value, so the back end will delay doing the mod operation (except in some scenarios).

> I also noticed that if I hard code rolV, the final result is as expected, 

When you hardcode rolV, then `uint_32 T = rolV + E; ` will assign a constant value to T, because E in your program is  `uint_32 E = H[4]; `, which is also a constant. Since doing the mod operation here is straightforward, and does not add any gates to the circuit, the mod is done automatically by the compiler, as it will minimize the range of the output variables in the next operations where such constant values are involved.

**Comment by sanchopansa** [comment]
I see, thanks for the feedback.
