### ISSUE TITLE
Cannot VerifyEq of large number multiplication

### ISSUE THREAD

**Issue by sylvarant** [akosba/xjsnark#2]
Large uint_ representation appears to be inconsistent?

In the attached example I multiply two uint_256 inputs into a uint_512 value.
I've verified that this multiplication produces the correct result within xjsnark.
However, when verifying the correctness of that multiplication against the correct result:
<img width="668" alt="huhh" src="https://user-images.githubusercontent.com/43544/47192801-d73ad880-d381-11e8-9634-f59a11c60c54.PNG">
The equality assertion fails which seems illogical.
<img width="579" alt="weird" src="https://user-images.githubusercontent.com/43544/47192857-37317f00-d382-11e8-8e1e-7b72b55aba26.PNG">

Test case is attached
[multiplicationTest.zip](https://github.com/akosba/xjsnark/files/2494106/multiplicationTest.zip)

**Comment by akosba** [comment]
This mainly happens because you do the conversion to uint_512 after the multiplication. This should be applied to one of operands _before_ multiplication. To simplify, think of long and int operations in java,
int i = 10000000;
int j = 10000000;
if you do either
long result = i * j;  or long result = (long)(i*j);
result is not going to be the expected 10e14. Instead, at least i or j need to be casted to long first.

So, to fix your code, the first line should be modified to uint_512 mul = uint_512(sig) * siginv;

Also for the red string in your code that has the expected value. The unsigned number string should end with 'u' (This notation is different from the paper example). By the way, if copy/pasting long number strings in this format is tricky in the environment, you can also do 
uint_512 corr_mul = uint_512("..");    // write the decimal string between quotes
See the EC_KeyKnowledge example for similar usages but in the case of fields. You could also write 
uint_512 corr_mul = 0u; 
and then replace the 0 with the long number.

**Comment by sylvarant** [comment]
Thanks for the response! 
Issue resolved.
