### ISSUE TITLE
Wrong constraint in APPENDIX B

### ISSUE THREAD

**Issue by magrady** [akosba/xjsnark#26]
Hi,

In subsection A.2) of APPENDIX B. of doc/paper_extended_version/xjsnark.pdf in the latest commit (c6be834),
I think constraint for the two-wire switch is wrong, while it may due to some typo. For a switch receiving two wires w1 and w2, the prover provides the first output wire as an external witness w1', such that (w1 − w1')(w2 − w1') = 0. In current version, the constraint will fail when (w1', w2') = (w2, w1). If my thoughts are wrong, please correct me.

Hope this can be fixed. Thanks.

**Comment by akosba** [comment]
Hi,

Yes, it's a typo. Thanks for letting me know. The constraint should be (w1 − w1')(w2 − **w1'**) = 0 instead of (w1 − w1')(w2 − **w2'**) = 0. This is meant to enforce that the external wire w1' is either equal to w1 or w2. I pushed an updated version of the pdf.

Note: the constraint is set correctly in the implementation. The typo is only in the pdf, so no updates were pushed to the back end jar. The switching circuit can be inspected in the output of the examples that have verify_permutation, like the sorting circuit. Please let me know if you have other questions or observations about this
