### ISSUE TITLE
Array index out of bounds in forceEquality2

### ISSUE THREAD

**Issue by jimmyqiji** [akosba/xjsnark#30]
Hi Ahmed, 

I have a program testing point addition on BN curves. 
```
private F_q[] addPoints(F_q[] p1, F_q[] p2) {
  F_q lambda = (p2[1] - p1[1]) / (p2[0] - p1[0]);
  ...
}
```

Where q is defined in FieldDefTable, and `p1`, `p2` are arrays of x and y coordinates. When running the program, I'm faced with the following error, and line 101 in the compiled java code refers to the first line in method addPoints.
![error](https://user-images.githubusercontent.com/32436316/112214710-e464ed00-8bf5-11eb-9b42-dccfd982e90c.png)

@akosba could you please help with this issue? Thanks a lot.
Also, could you explain when to use the config `Config.setFiniteFieldModulus(new BigInteger(".."));`?

**Comment by akosba** [comment]
Hi, 
- Could you provide more details regarding your program, so that I can run a similar code and address the cause of the exception? For example, what is the value of q? Are the arguments provided to addPoints() declared as circuit inputs, or the result of other operations? 

`Also, could you explain when to use the config ..
`
- For the configuration method you are asking about, this is used to change the native field. This is done when we change the curves used by the zk-SNARK backend. For example, if you check this directory in libff: https://github.com/scipr-lab/libff/tree/04094606d6e90f4d6a2d6a9d32a3a5a660b67bd4/libff/algebra/curves, you will find a set of curves. The default configuration in xJsnark is consistent with the default curves used in libsnark for the proof systems we target. If the backend is configured to use the MNT4 curve instead, we will have to make the circuits produced using xJsnark consistent. To do that, we will have to call the configuration method with the scalar field Fr parameter corresponding to MNT4: https://github.com/scipr-lab/libff/blob/04094606d6e90f4d6a2d6a9d32a3a5a660b67bd4/libff/algebra/curves/mnt/mnt4/mnt4_init.cpp#L48.

**Comment by jimmyqiji** [comment]
Hello, 

Thank you for the quick reply! 
I used a value of `205523667896953300194896352429254920972540065223` for `q`. 
After a little experimenting, changing `q` to a smaller `164337599208824281` gets past the error, excuse my ignorance, but why is this the case? In the example ECKeyKnowledge, `p256` is an even larger prime and it works fine.

Attached .mps file for reference: 
[bnCurve.zip](https://github.com/akosba/xjsnark/files/6199770/bnCurve.zip)

**Comment by akosba** [comment]
Thanks for reporting the issue. 

The reason this IndexOutOfBoundsException was generated is due to a special case that was not handled in the implementation of multiprecision arithmetic. The exception happens when the grouping optimization used for asserting the equality of two long elements results only in one grouped chunk. You can see the corresponding fix that I have just pushed to jsnark: https://github.com/akosba/jsnark/commit/30aad788724f0752b429c1f4c9c94aabe2e34636

This did not appear in the case when q = 164337599208824281, because the value of q here is small w.r.t. the native field used, so multiprecision arithmetic is not used and xJsnark adapts the implementation accordingly in this case. The exception also did not appear when larger modulus values were used as in the provided EC and RSA examples, because values above a certain value will not have the above special case.

**Comment by jimmyqiji** [comment]
Thank you for the explanations and the timely fix! Appreciate it.
