### ISSUE TITLE
Cannot use large number as a literal in method outsource()

### ISSUE THREAD

**Issue by m1cm1c** [akosba/xjsnark#32]
## Steps to reproduce

1. Open any XJSnark program file.
2. In method `outsource()`, try to type the following into a new line: `uint_80 t = 12345678912`

## Problems
1. The line will read: `uint_80 t = 0;`
2. It is impossible to get a large number as a literal into method `outsource()`, even when using copying + pasting or trying to merge literals you typed separately.

**Comment by akosba** [comment]
You can either do:
uint_80 t = uint_80("12345678912");
or
uint_80 t = 12345678912u;

The reason you saw 0 in your case is because MPS in this version assumes that the numeric literal  must fit within the java int by default, and it turns the literal to zero if it is out of range while editing. To get around this while editing using the second way is starting by uint_80 t = 1u; then add the digits, or use the first method directly, which avoids this.
