### ISSUE TITLE
Miscompilation of if else statement in for loop

### ISSUE THREAD

**Issue by sylvarant** [akosba/xjsnark#4]
The following loop iterates over an if else statement that ends the loop if (uint_256 n < 0)
![error](https://user-images.githubusercontent.com/43544/48176534-6d439c80-e34b-11e8-8a7d-aff1770abd33.PNG)
However that else statement (the n < 0 case assigning j to 256) is getting miscompiled ? As the result of this function is always [0,0] when this else statement is included but the function works fine without it.

Example attached:
[ECDSAVerify_error.zip](https://github.com/akosba/xjsnark/files/2560229/ECDSAVerify_error.zip)

**Comment by sylvarant** [comment]
If I replace 
`(n > zero256)` with 
`(n != zero256)` 
where zero256 is just a globally defined uint_256(0), I don't have this issue?

**Comment by akosba** [comment]
The reason for this issue is that you are trying to assign a native type variable inside a conditional block that is dependent on runtime values. What can only be assigned or changed in these blocks are xjsnark types.

More importantly, it won't help to make j = 256 in that case. In cases like this, we have to assume the maximum number of iterations happening anyway, as we are writing a circuit. This is different from typical scenarios, where breaking earlier would save us some steps, but here we are building a circuit that should handle any kind of input.

This means that your code can be written in a simpler way to achieve the same objective, for example, I think it can written like the following:

```
for(int j = 0; j < 256; j++){
    if(n.bits[j]){       // replaced 0 by j, to avoid shifting
           if(j < 1){
                  ax = .. ;
                  ay = .. ;
           } else {
                    F_p256[] r2 = addFP ( .. );
                    ax = .. ;
                   ay = .. ;           
         }
    }
    F_p256[] r2 = doubleFP ( ..);
    rx = ..;
    ry = ..;
}
```

Note that there are no more conditions checking n, or shifting. To see why this is not needed:  If there are no more 1 bits in n, the variables ax and ay will never get assigned again. I think you were likely trying to save the unnecessary doubleFP( .. ) calls, but as I mentioned earlier, it won't help here. Feel free to ask me if you have more questions.

**Comment by sylvarant** [comment]
Thanks for the reply!

So whenever you have to loop over a run-time input, it's best to simply design a native loop for the worst case scenario? Say you want to do some action X times, where X is a circuit input, it is then best to build a native loop for the maximum value of x ?

**Comment by akosba** [comment]
I won't call it best, as in some cases you might be able to do better. However, in cases like your code above, that's the right option.

If you are wondering about when we can do better or write these loops differently, you might find the following relevant:
- Let's assume we have a nested loop, and the bounds on both are run-time dependent. If we just rewrite the loops for the worst case scenario, we will end up with a quadratic circuit, and for some programs, this might not be needed.  You can check Figure 6 in the Buffet [paper](https://eprint.iacr.org/2014/674.pdf) for example to see how nested loops can be transformed to a more efficient version. Note that the above transformation will still require the programmer to input a bound on the total number of expected steps using a special keyword (See Section 4.1 in the Buffet paper).

- Also, if a universal circuit is used, like the case of the vnTinyRam [paper](https://eprint.iacr.org/2013/879.pdf), you might not need to set a bound for every separate loop, but only for the total number of program steps.  Although this sounds more flexible than the above, the universal approach adds cost compared to custom circuits like what Buffet and xJsnark generate.

**Comment by sylvarant** [comment]
Ok, thanks so much for the feedback! The computational bounds and differences between run time and native values are much more important than I initially realized.
