### ISSUE TITLE
Computation of modulus on-circuit

### ISSUE THREAD

**Issue by sanchopansa** [akosba/xjsnark#7]
I'm trying to understand what is the best way of computing a modulus operation on the product of two _unsigned integers_ in the `outsource` method.

My current understanding is that this is not so trivial, so I was very pleasantly surprised to see the `%` operator. I tried:
```java
public void outsource() {
  uint256 x = 1234;
  uint256 y = 10;
  uint256 z = x % y;
}
```
However, this produces the same output as `x / y`, namely `123`. I would expect it to produce `4`. What is the intended behavior?

My second thinking was to do the multiplication using two `uint_N` and feed the result in a `F_p` element, where `p` is appropriately chosen. I tried several different ways of doing so to no avail and the only thing I have been able to get to compile thus far is:
```java
public void outsource() {
  BigInteger x = new BigInteger("20"); 
  BigInteger y = new BigInteger("100"); 
  e = F_p(x.multiply(y)); 
}
```
Now I'm wondering how `BigInteger` operations (or operations on other Java-native types) are handled on-circuit. In the above `outsource` method, is `2000` a constant, or is the multiplication actually done in the circuit? Looking at the number of constraints and thinking about it, I am pretty sure it has to be a constant, but just wanted to confirm.

If it is indeed a constant, I still have the problem of computing the modulus of a product of two integers in the circuit... Is there some built-in way to accomplish this with `xjsnark`?

**Comment by akosba** [comment]
>  What is the intended behavior?

It should be the remainder. The method was just returning the division result instead of the mod result in case of constants. I fixed it.

> Now I'm wondering how BigInteger operations (or operations on other Java-native types) are handled on-circuit. In the above outsource method, is 2000 a constant, or is the multiplication actually done in the circuit? Looking at the number of constraints and thinking about it, I am pretty sure it has to be a constant, but just wanted to confirm.

It's a constant. The backend aims to avoid adding any constraints that can be resolved at compilation time.

> I'm trying to understand what is the best way of computing a modulus operation on the product of two unsigned integers in the outsource method.

The ideal way to handle this in my opinion is to support Field Types that has arbitrary modulus known only at runtime. I am going to add support for this soon to the front end. The backend can make the operations more efficient than when using % operator on long integers. 

For now, may be you can try using the modulus operations as you originally planned, and let me know how it goes. I admittedly could not test all possible scenarios yet..

**Comment by sanchopansa** [comment]
Thanks for fixing this. Seems to be working for on a couple of basic examples I tried. I will let you know if I hit any issues.

> The ideal way to handle this in my opinion is to support Field Types that has arbitrary modulus known only at runtime. I am going to add support for this soon to the front end. The backend can make the operations more efficient than when using % operator on long integers.

Allowing parameterization of the fields at compile time, which is currently supported, is already quite useful (and impressive). If specifying a modulus at run time is added, it would be even nicer! Could you point me to a paper describing what kind of optimizations would be possible? I would be interested to learn more.

If I may, one question that is somewhat related to what I asked above: is there a way to convert a `unit_N` to a `F_p` in the circuit? I wasn't able to get it to work. I was hoping that something like:

```
uint_256 x = 1234234234;
F_p y = F_p(x);
```
would work, but I'm getting compilation errors.

**Comment by akosba** [comment]
> Allowing parameterization of the fields at compile time, which is currently supported, is already quite useful (and impressive). If specifying a modulus at run time is added, it would be even nicer! Could you point me to a paper describing what kind of optimizations would be possible? I would be interested to learn more.

You can find some optimizations in the xJsnark paper. By the way, it's not only about optimizations. If the mod decision is left to the programmer, the programmer will be responsible for choosing where it's best to apply the mod operation, and what should be the size of the integers holding the operand data. For example if you assume that your function computes` (a * b + c * d * f ) mod N` manually, you will have to choose where to apply the mod operations. Should it be in the end, or should it be after every multiplication, or should it be something else?  Note that if we wait till the end, the result might be incorrect because internal overflows might occur, so the programmer will need to keep track of the maximum value on the involved wires before applying any further operations (This will require knowledge of how the back end works). On the other hand, if you do the mod after every operation, it's not going to be efficient. You can find a discussion on this problem in the paper. In the current released version, the back end applies some heuristics to get good performance for short and long integer operations while avoiding overflows and reducing the programmer's overhead. Advanced optimization techniques are also possible, although they won't scale for very large circuits, but we can make use of the fact that some of these circuits might be small (operation-wise), so we can find the optimal for some cases. I have not pushed that yet.

For adding parametrized field types with unknown modulus during compilation time, it's already in the plan.

> If I may, one question that is somewhat related to what I originally was trying to do: is there a way to convert a uint_N to a F_p in the circuit? I wasn't able to get it to work. I was hoping that something like:
> 
> uint_256 x = 1234234234;
> F_p y = F_p(x);
> would work, but I'm getting compilation errors.

Will try to add support for that during the next few days. I think I had only one direction of conversion working at this point.

**Comment by sanchopansa** [comment]
Yes, I understand the problems that can arise because of overflows. I will have a look at the paper in more detail to see how you currently handle it.

One question: when you say that the programmer should be responsible for choosing what is the size of the integers holding the operand data, do you mean that if I work with say 4-bit `uint`s and I want to multiply two numbers and take the modulus of the product, I would actually have to store the `uint`s in 8-bits in order to prevent an overflow of an operation such as:
```
uint_4 a = 5;
uint_4 b = 12;
uint_4 c = (a * b) mod 13
```

> Will try to add support for that during the next few days. I think I had only one direction of conversion working at this point.

That would be awesome!

**Comment by akosba** [comment]
> One question: when you say that the programmer should be responsible for choosing what is the size of the integers holding the operand data, do you mean that if I work with say 4-bit uints and I want to multiply two numbers and take the modulus of the product, I would actually have to store the uints in 8-bits in order to prevent an overflow of an operation such:
> where (a * b) would overflow as the result will also be stored in a 4-bit integer?
Yes, this is what I meant.
